dist: precise # https://github.com/travis-ci/travis-ci/issues/8331
addons:
  apt:
    packages:
      - sqlite3 # https://github.com/rails/rails/issues/24288#issuecomment-206011385
language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
rvm:
  - 2.2.3
  - 2.3.4
  - '2.4'

matrix:
  fast_finish: true
  include:
    - rvm: 2.2.3
      env: SUITE=rubocop

notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
