addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3 # https://github.com/rails/rails/issues/24288#issuecomment-206011385
language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
rvm:
  - 2.3.1
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.1
      env: SUITE=rubocop

notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
