host: 'shipit-engine.myshopify.io'
redis_url: 'redis://shipit-engine.railgun:6379'

# TODO: document creating a dev app
github:
  app_id:
  installation_id:
  webhook_secret: # nil
  private_key:
  oauth:
    id:
    secret:
    teams:
