host: 'http://localhost:3000'
redis_url: 'redis://127.0.0.1:6379/0'

github_api:
  # Can be obtained there: https://github.com/settings/tokens/new
  # The required permissions are: `admin:org_hook`, `admin:repo_hook`, `read:org` and `repo`
  access_token:

# Can be obtained there: https://github.com/settings/applications/new
# Set the "Authorization callback URL" as `<host>/github/auth/github/callback`
github_oauth: 
  id:
  secret:
  # teams: # Optional

# To work on the beta bootstrap re-write
# features:
#   - bootstrap

# To work on the kubernetes deploy script
# env:
#   KUBECONFIG: # Path of the kubeconfig you want to use.
#   GOOGLE_APPLICATION_CREDENTIALS: # Used if your kube auth provider is gcp, in which case it should be path of the service account credentials you want to use. Alternatively, you can run `gcloud auth application-default login` (and remove this variable) to use your own google account locally.
